site_name: Développement d’applications sous processeur graphique (GPU / CUDA).
repo_url: https://github.com/matEhickey/Projet-CUDA-M2
site_description: Documentation projet M2 CUDA
site_author: Mathias DIDIER
site_favicon: favicon.ico

pages:
- Home: index.md
- Introduction: introduction.md
- Jetson TK1: tk1.md
- Connexions: connexions.md
- CPU/GPU: cpu_gpu.md
- Architectures: architecture.md
- CUDA: cuda.md
- Frameworks: frameworks.md
- Tensorflow: tensorflow.md
- Applications: applications.md
- Traitement d'image: traitementImage.md
- Optimisation GPU: optimisation.md
- Optimisation/Reduction: reduction.md
- Reconnaissance des signes: signRecognition.md
- Ressources: ressources.md
- Outils: outils.md
- About: about.md
- Scéances: sceances.md
- Installations: installations.md
theme: readthedocs
